### ISSUE TITLE
元のサイトと微妙にデザインが違う

### ISSUE THREAD

**Issue by xxj** [TeamMomentum/TeamMomentum.github.io#6]
フォントが微妙に違う
CSSのリンク切れ？

**Comment by dictav** [comment]
フォントですね。
HTMLが `http` プロトコルを指定しているので、https でアクセスすると崩れます。

**Comment by dictav** [comment]
新しいデザインが着工しましたので、こちらクローズします。

**Comment by dictav** [comment]
今後新デザインとかやるなら fork するのが良いのだろうなー
